/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.*;
import Persistencia.*;
import javax.swing.JOptionPane;
import Logica.Index;
import java.awt.Point;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/**
 *
 * @author ayr_1
 */
public class ModificarDatosTitular extends javax.swing.JFrame {
    private Persona persona;
    private PersonaController personaController;
    private String calle, numero, piso, dpto;
    private Point mouseDownCompCoords = null;

    /**
     * Creates new form ModificarDatosUsuario
     */
    //Contructor
    public ModificarDatosTitular(Persona persona, PersonaController personacontroller) {
        initComponents();
        this.persona = persona;
        this.personaController = personacontroller;
        cargarCampos();
        setIconImage(new ImageIcon(getClass().getResource("/favicon.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Index.historial.add(this);        
    }
    
    //Completo la interfaz con los datos del titular que fue elegido
    private void cargarCampos(){
        this.jLabelTipoID.setText(persona.getTipoId());
        this.jLabelID.setText(persona.getNroId());
        this.jTextFieldNombre.setText(persona.getNombre());
        this.jTextFieldApellido.setText(persona.getApellido());
        this.jLabelFechaN.setText(persona.getFechaNac().toString());
        
        //Creo un tokenizer para obtener los datos del domicilio por separado y así poder modificarlos y/o validarlos
        String domicilio = persona.getDomicilio();
        StringTokenizer st = new StringTokenizer(domicilio);
        
        if (st.hasMoreTokens()){
            this.calle=st.nextToken();
            this.jTextFieldCalle.setText(calle);
        }
        if (st.hasMoreTokens()){
            this.numero= st.nextToken();
            this.jTextFieldNumeroCalle.setText(numero);
        }
        if (st.hasMoreTokens()){
            this.piso= st.nextToken();
            this.jTextFieldPiso.setText(piso);
        }
        if (st.hasMoreTokens()){
            this.dpto= st.nextToken();
            this.jTextFieldDepartamento.setText(dpto);
        }
        if (this.persona.isDonante()){
            this.jRadioButtonDonanteSi.setSelected(true);
        }
        else{
            this.jRadioButtonDonanteNo.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        privilegios = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        botonCerrar = new javax.swing.JButton();
        botonMinimizar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabelDocumento = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombreTitular = new javax.swing.JLabel();
        jLabelApellidoTitular = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelCalle = new javax.swing.JLabel();
        jTextFieldCalle = new javax.swing.JTextField();
        jLabelNumeroDireccion = new javax.swing.JLabel();
        jTextFieldNumeroCalle = new javax.swing.JTextField();
        jTextFieldPiso = new javax.swing.JTextField();
        jLabelPiso = new javax.swing.JLabel();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelDonante = new javax.swing.JLabel();
        jRadioButtonDonanteSi = new javax.swing.JRadioButton();
        jRadioButtonDonanteNo = new javax.swing.JRadioButton();
        jLabelTipoID = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelFechaNac = new javax.swing.JLabel();
        jLabelFechaN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(206, 206, 206));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true)));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/EditTitular.png"))); // NOI18N
        jLabel14.setText(" Modificar Titular");
        jLabel14.setFocusable(false);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator4.setOpaque(true);

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/cancel.png"))); // NOI18N
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setFocusable(false);
        botonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/cancel rollover.png"))); // NOI18N
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/diminish.png"))); // NOI18N
        botonMinimizar.setBorderPainted(false);
        botonMinimizar.setContentAreaFilled(false);
        botonMinimizar.setFocusable(false);
        botonMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/diminish rollover.png"))); // NOI18N
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/left-arrow.png"))); // NOI18N
        botonAtras.setBorderPainted(false);
        botonAtras.setContentAreaFilled(false);
        botonAtras.setFocusable(false);
        botonAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/left-arrow rollover.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonActualizar.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Flecha derecha.png"))); // NOI18N
        botonActualizar.setBorderPainted(false);
        botonActualizar.setContentAreaFilled(false);
        botonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonActualizarMouseExited(evt);
            }
        });
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        botonActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonActualizarKeyTyped(evt);
            }
        });

        jLabelDocumento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelDocumento.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDocumento.setText("Documento");

        jTextFieldNombre.setToolTipText("32 caracteres como maximo");
        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNombreTitular.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelNombreTitular.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombreTitular.setText("Nombre");

        jLabelApellidoTitular.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelApellidoTitular.setForeground(new java.awt.Color(51, 51, 51));
        jLabelApellidoTitular.setText("Apellido");

        jTextFieldApellido.setToolTipText("32 caracteres como maximo");

        jLabelDireccion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDireccion.setText("Dirección");

        jLabelCalle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelCalle.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCalle.setText("Calle");

        jTextFieldCalle.setToolTipText("");

        jLabelNumeroDireccion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelNumeroDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNumeroDireccion.setText("Número");

        jTextFieldPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPisoActionPerformed(evt);
            }
        });

        jLabelPiso.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelPiso.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPiso.setText("Piso");

        jTextFieldDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDepartamentoActionPerformed(evt);
            }
        });

        jLabelDepartamento.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelDepartamento.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDepartamento.setText("Departamento");

        jLabelDonante.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelDonante.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDonante.setText("Donante");

        jRadioButtonDonanteSi.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jRadioButtonDonanteSi.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonDonanteSi.setText("Si");
        jRadioButtonDonanteSi.setContentAreaFilled(false);
        jRadioButtonDonanteSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDonanteSiActionPerformed(evt);
            }
        });

        jRadioButtonDonanteNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jRadioButtonDonanteNo.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonDonanteNo.setText("No");
        jRadioButtonDonanteNo.setContentAreaFilled(false);
        jRadioButtonDonanteNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDonanteNoActionPerformed(evt);
            }
        });

        jLabelTipoID.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelTipoID.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTipoID.setText("Nombre");

        jLabelID.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(51, 51, 51));
        jLabelID.setText("Nombre");

        jLabelFechaNac.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelFechaNac.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFechaNac.setText("Fecha de nacimiento");

        jLabelFechaN.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelFechaN.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFechaN.setText("Nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonActualizar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelApellidoTitular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabelTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabelFechaNac)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabelCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabelNumeroDireccion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabelPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(54, 54, 54)
                                            .addComponent(jLabelDepartamento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabelDonante, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButtonDonanteSi)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonDonanteNo))))))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelApellidoTitular)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNumeroDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDepartamento)
                        .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPiso)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDonante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDonanteSi)
                    .addComponent(jRadioButtonDonanteNo))
                .addGap(15, 15, 15)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_botonMinimizarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        Index.historial.get(Index.historial.size()-2).setVisible(true);
        this.dispose();
        Index.historial.remove(Index.historial.size()-1);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseEntered
        this.botonActualizar.setBackground(this.botonActualizar.getBackground().darker());
    }//GEN-LAST:event_botonActualizarMouseEntered

    private void botonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseExited
        this.botonActualizar.setBackground(this.botonActualizar.getBackground().brighter());
    }//GEN-LAST:event_botonActualizarMouseExited

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        //Valido los datos  ingresados y dependiendo del resultado muestro el mensaje correspondiente
        switch (personaController.validarDatosMT(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(), this.jTextFieldCalle.getText() ,this.jTextFieldNumeroCalle.getText(), this.jTextFieldPiso.getText(), this.jTextFieldDepartamento.getText())){
            case 0:
            try {
                //Actualizo la persona existente
                persona.setNombre(this.jTextFieldNombre.getText());
                persona.setApellido(this.jTextFieldApellido.getText());
                this.calle=this.jTextFieldCalle.getText();
                this.numero=this.jTextFieldNumeroCalle.getText();
                this.piso=this.jTextFieldPiso.getText();
                this.dpto=this.jTextFieldDepartamento.getText();
                
                persona.setDomicilio(calle+" "+numero+" "+piso+" "+dpto);
                persona.setDonante(jRadioButtonDonanteSi.isSelected());
                //Actualizo en la BD
                personaController.updateTitular(persona);
                //Muestro mensaje de exito
                JOptionPane.showMessageDialog(this, "Ha actualizado el titular con éxito", "Felicidades",  JOptionPane.INFORMATION_MESSAGE);
                //Vuelvo a la pantalla de buscar titular
                Index.historial.get(Index.historial.size()-2).setVisible(true);
                this.dispose();
                Index.historial.remove(Index.historial.size()-1);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "La contraseña no es válida", "Error",  JOptionPane.ERROR_MESSAGE);
            }
            break;
            case 1:
            JOptionPane.showMessageDialog(this, "El nombre no es correcto", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
            case 2:
            JOptionPane.showMessageDialog(this, "El apellido no es correcto", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
            case 3:
            JOptionPane.showMessageDialog(this, "La calle insertada no es correcto o la extensión del domicilio supera el límite(32)", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
            case 4:
            JOptionPane.showMessageDialog(this, "El número de calle insertado no es válido", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
            case 5:
            JOptionPane.showMessageDialog(this, "El número de piso insertado no es válido", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
            case 6:
            JOptionPane.showMessageDialog(this, "El departamento insertado no es válido", "Error",  JOptionPane.ERROR_MESSAGE);
            break;
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonActualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonActualizarKeyTyped
        
    }//GEN-LAST:event_botonActualizarKeyTyped

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        Point currCoords = evt.getLocationOnScreen();
        this.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        mouseDownCompCoords = evt.getPoint();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased
        mouseDownCompCoords = null;
    }//GEN-LAST:event_jPanel4MouseReleased

    private void jTextFieldPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPisoActionPerformed

    private void jTextFieldDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDepartamentoActionPerformed

    private void jRadioButtonDonanteNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDonanteNoActionPerformed
        if (jRadioButtonDonanteSi.isSelected()){
            jRadioButtonDonanteSi.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDonanteNoActionPerformed

    private void jRadioButtonDonanteSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDonanteSiActionPerformed
        if (jRadioButtonDonanteNo.isSelected()){
            jRadioButtonDonanteNo.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDonanteSiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonMinimizar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabelApellidoTitular;
    private javax.swing.JLabel jLabelCalle;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelDonante;
    private javax.swing.JLabel jLabelFechaN;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombreTitular;
    private javax.swing.JLabel jLabelNumeroDireccion;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelTipoID;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonDonanteNo;
    private javax.swing.JRadioButton jRadioButtonDonanteSi;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroCalle;
    private javax.swing.JTextField jTextFieldPiso;
    private javax.swing.ButtonGroup privilegios;
    // End of variables declaration//GEN-END:variables
}
