package Persistencia;
// Generated 07/11/2018 01:09:07 by Hibernate Tools 4.3.1



/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private String id;
     private String vehiculos;
     private int edadMinima;
     private String clasesHeredadasId;

    public Clase() {
    }

	
    public Clase(String id, String vehiculos, int edadMinima) {
        this.id = id;
        this.vehiculos = vehiculos;
        this.edadMinima = edadMinima;
    }
    public Clase(String id, String vehiculos, int edadMinima, String clasesHeredadasId) {
       this.id = id;
       this.vehiculos = vehiculos;
       this.edadMinima = edadMinima;
       this.clasesHeredadasId = clasesHeredadasId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(String vehiculos) {
        this.vehiculos = vehiculos;
    }
    public int getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(int edadMinima) {
        this.edadMinima = edadMinima;
    }
    public String getClasesHeredadasId() {
        return this.clasesHeredadasId;
    }
    
    public void setClasesHeredadasId(String clasesHeredadasId) {
        this.clasesHeredadasId = clasesHeredadasId;
    }




}


