package Persistencia;
// Generated 07/11/2018 01:09:07 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String username;
     private byte[] password;
     private boolean privilegio;

    public Usuario() {
    }

    public Usuario(String username, byte[] password, boolean privilegio) {
       this.username = username;
       this.password = password;
       this.privilegio = privilegio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public boolean isPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(boolean privilegio) {
        this.privilegio = privilegio;
    }




}


