package Persistencia;
// Generated 06/11/2018 23:10:19 by Hibernate Tools 4.3.1



/**
 * Vigencias generated by hbm2java
 */
public class Vigencias  implements java.io.Serializable {


     private Integer id;
     private String condicion;
     private int duracion;

    public Vigencias() {
    }

    public Vigencias(String condicion, int duracion) {
       this.condicion = condicion;
       this.duracion = duracion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


